name: "Jekyll Live Builder"
slug: "jekyll_live"
version: "1.0.7"
description: "Run Jekyll locally for static-site building to serve on your Home Assistant instance"
startup: "services"
boot: "manual"
arch:
  - amd64
init: false

map:
  - type: homeassistant_config
    read_only: false
    path: /config

options:
  jekyll_dir: "/config/jekyll"
  output_dir: "/config/www"
  incremental: false
  one_shot: false
  custom_args: ""

schema:
  jekyll_dir: "str"
  output_dir: "str"
  incremental: "bool"
  one_shot: "bool"
  custom_args: "str"
